### PR TITLE
fix: correctly parse weekday ranges that include sunday

### LINKED ISSUE #282: Weekday range to sunday edge case
Heyho,

there is a little bug when using a range for weekdays which includes sunday as '7', due to the replacement with '0'.

I.e.: `5 10 * * 6-7` will throw `Failed to parse 6-7: Invalid range (start: 6, end: 0).`

### PR DESCRIPTION
**Pull request by sky0hunter**
This should solve the issue with parsing ranges like `6-7` for the weekday.

The tests are passing and with that small post processing of the weekdays element ( modulo + set -> remove duplicates and still have 0-6 ) it should do the exact same thing as before.

It should fix #282

### CODE REVIEW

**Comment by P4sca1** [comment]
Thank you for the PR. I will look into it within the next days. I think the problem still persists when using aliases, e.g. sat-sun, right?

**Comment by sky0hunter** [comment]
I've added another commit which changes the `sun` alias to `7`, so now these kind of ranges will work with them too.

**Pull request merged**
